name: rag-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.11.0
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - build==1.3.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - chromadb==1.3.4
      - click==8.3.0
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==4.4.1
      - deprecated==1.3.1
      - dill==0.4.0
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - docstring-parser==0.17.0
      - durationpy==0.10
      - effdet==0.4.1
      - emoji==2.15.0
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - filetype==1.2.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-cloud-vision==3.11.0
      - googleapis-common-protos==1.72.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - html5lib==1.1
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - identify==2.6.15
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - instructor==1.13.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - kubernetes==34.1.0
      - langchain==1.0.7
      - langchain-chroma==1.0.0
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.0.5
      - langchain-huggingface==1.0.1
      - langchain-openai==1.0.2
      - langchain-text-splitters==1.0.0
      - langdetect==1.0.9
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.4
      - langgraph-sdk==0.2.9
      - langsmith==0.4.42
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mmh3==5.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nltk==3.9.2
      - nodeenv==1.9.1
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - olefile==0.47
      - omegaconf==2.3.0
      - onnx==1.19.1
      - onnxruntime==1.23.2
      - openai==2.8.0
      - opencv-python==4.12.0.88
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-grpc==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pdf2image==1.17.0
      - pdfminer-six==20251107
      - pi-heif==1.1.1
      - pikepdf==10.0.2
      - pillow==11.3.0
      - platformdirs==4.5.0
      - posthog==5.4.0
      - pre-commit==4.4.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pycocotools==2.0.10
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pypdf==6.2.0
      - pypdfium2==5.0.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-iso639==2025.11.11
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-oxmsg==0.0.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - ragas==0.3.9
      - rapidfuzz==3.14.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scikit-network==0.33.4
      - scipy==1.15.3
      - sentence-transformers==5.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sympy==1.13.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - timm==1.0.22
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.1.0
      - ty==0.0.1a26
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - unstructured==0.18.18
      - unstructured-client==0.42.4
      - unstructured-inference==1.1.1
      - unstructured-pytesseract==0.3.15
      - urllib3==2.3.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - virtualenv==20.35.4
      - watchfiles==1.1.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /root/miniconda3/envs/rag-env
